name: create-posts

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/temp/**'

env:
  RUST_DIR: ./packages/rust-craft-data-process
  POST_DIR_FROM_RUST_DIR: ../../_contents/posts
  INPUT_DIR_FROM_RUST_DIR: ../../.github/temp
  INPUT_JSON: craft_raw.json

jobs:
  create-posts:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Build rust-craft-data-process
        working-directory: ${{ env.RUST_DIR }}
        run: cargo build --verbose

      - name: Create posts
        working-directory: ${{env.RUST_DIR}}
        run: RUST_BACKTRACE=1 cargo run --verbose $INPUT_DIR_FROM_RUST_DIR/$INPUT_JSON $POST_DIR_FROM_RUST_DIR

      - name: Commit to blog page branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'published by CraBft 🦀'
          file_pattern: _contents/*
          commit_user_name: CraBft 🦀 # defaults to "GitHub Actions"
          skip_dirty_check: true
          disable_globbing: true
          commit_options: '--no-verify --signoff'
          push_options: '--force'
