name: gh-pages deploy
on:
  workflow_run:
    workflows: ['create-posts']
    types:
      - completed
env:
  BLOG_PAGE_BRANCH: main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Set blog page target branch
        env:
          USE_CUSTOM_BRANCH: ${{ secrets.USE_CUSTOM_BRANCH }}
        if: ${{ env.USE_CUSTOM_BRANCH }}
        run: |
          echo "BLOG_PAGE_BRANCH=blog-pages" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BLOG_PAGE_BRANCH }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependency
        run: yarn install

      - name: Build
        run: yarn run blog:export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./packages/nextjs-craft-blog-kit/out
